# This is a basic workflow to help you get started with Actions

name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with maven
        run: mvn -B package --file pom.xml
      - name: tomcat deploy
        run: curl -v -u admin:admin -T /home/ec2-user/actions-runner/_work/spring3-mvc-maven-xml-hello-world/spring3-mvc-maven-xml-hello-world/target/spring3-mvc-maven-xml-hello-world-1.2.war 'http://ec2-54-242-145-79.compute-1.amazonaws.com:8080/manager/text/deploy?path=/github_deploy&update=true'
